// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace stockanalysis.Migrations
{
    [DbContext(typeof(StockAnalysisContext))]
    partial class StockAnalysisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CombinedStockData", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("AnalystCount")
                        .HasColumnType("int");

                    b.Property<string>("AnalystRatings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Change1Month")
                        .HasColumnType("float");

                    b.Property<double>("Change1Week")
                        .HasColumnType("float");

                    b.Property<double>("Change1Year")
                        .HasColumnType("float");

                    b.Property<double>("Change3Years")
                        .HasColumnType("float");

                    b.Property<double>("Change5Years")
                        .HasColumnType("float");

                    b.Property<double>("Change6Months")
                        .HasColumnType("float");

                    b.Property<double>("ChangeYearToDate")
                        .HasColumnType("float");

                    b.Property<double>("DividendGrowth")
                        .HasColumnType("float");

                    b.Property<double>("DividendPerShare")
                        .HasColumnType("float");

                    b.Property<double>("DividendYield")
                        .HasColumnType("float");

                    b.Property<double>("EarningsPerShare")
                        .HasColumnType("float");

                    b.Property<long>("EnterpriseValue")
                        .HasColumnType("bigint");

                    b.Property<long>("FreeCashFlow")
                        .HasColumnType("bigint");

                    b.Property<string>("IndustrySector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MarketCapitalization")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NetIncome")
                        .HasColumnType("bigint");

                    b.Property<long>("OperatingIncome")
                        .HasColumnType("bigint");

                    b.Property<double>("PFcfRatio")
                        .HasColumnType("float");

                    b.Property<string>("PayoutFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PayoutRatio")
                        .HasColumnType("float");

                    b.Property<double>("PbRatio")
                        .HasColumnType("float");

                    b.Property<double>("PeForward")
                        .HasColumnType("float");

                    b.Property<double>("PriceChange")
                        .HasColumnType("float");

                    b.Property<double>("PriceEarningsRatio")
                        .HasColumnType("float");

                    b.Property<double>("PriceTarget")
                        .HasColumnType("float");

                    b.Property<double>("PriceTargetChange")
                        .HasColumnType("float");

                    b.Property<double>("PsRatio")
                        .HasColumnType("float");

                    b.Property<long>("Revenue")
                        .HasColumnType("bigint");

                    b.Property<double>("StockPrice")
                        .HasColumnType("float");

                    b.Property<long>("TradingVolume")
                        .HasColumnType("bigint");

                    b.HasKey("Symbol", "Date");

                    b.ToTable("CombinedStockData");
                });

            modelBuilder.Entity("CryptoAnalysis+CryptoData", b =>
                {
                    b.Property<string>("BaseCurrency")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("BaseCurrencyDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CloseChange24h")
                        .HasColumnType("float");

                    b.Property<int>("CryptoTotalRank")
                        .HasColumnType("int");

                    b.Property<double>("MarketCapCalc")
                        .HasColumnType("float");

                    b.Property<double>("Perf1M")
                        .HasColumnType("float");

                    b.Property<double>("Perf3M")
                        .HasColumnType("float");

                    b.Property<double>("Perf5Y")
                        .HasColumnType("float");

                    b.Property<double>("Perf6M")
                        .HasColumnType("float");

                    b.Property<double>("PerfAll")
                        .HasColumnType("float");

                    b.Property<double>("PerfW")
                        .HasColumnType("float");

                    b.Property<double>("PerfY")
                        .HasColumnType("float");

                    b.Property<double>("PerfYTD")
                        .HasColumnType("float");

                    b.Property<double>("Vol24hCmc")
                        .HasColumnType("float");

                    b.Property<double>("VolatilityD")
                        .HasColumnType("float");

                    b.HasKey("BaseCurrency", "Date");

                    b.ToTable("CombinedCryptoData");
                });
#pragma warning restore 612, 618
        }
    }
}
